# Set the internal Log4j2 status logging level
status = warn

# Define a console appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %style{%d{HH:mm:ss.SSS}}{cyan} %style{[%t]}{magenta} %highlight{%-5level}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=green, DEBUG=green bold, TRACE=blue} %style{%logger{36}}{yellow} - %style{%msg}{green}%n

# Configure the root logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
